apiVersion: v2
name: prowlarr
description: Prowlarr (indexer manager) via bjw-s app-template. FlareSolverr, PostgreSQL, 1Password. Override ingress, persistence, postgresql in your values.
version: 1.0.0
appVersion: "1.22.0"
kubeVersion: ">=1.22.0-0"
keywords:
  - prowlarr
  - indexer
  - bjw-s
  - app-template
home: https://prowlarr.com
sources:
  - https://github.com/Prowlarr/Prowlarr
maintainers: []
dependencies:
  - name: app-template
    alias: prowlarr
    version: "4.6.2"
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: flaresolverr
    version: "v5.4.2"
    repository: https://k8s-at-home.com/charts
  - name: onepassworditem
    version: "1.1.1"
    repository: https://expectedbehaviors.github.io/OnePasswordItem-helm
  - name: postgresql
    version: "16.2.1"
    repository: https://charts.bitnami.com/bitnami
